### ISSUE TITLE
Random number generation

### ISSUE THREAD

**Issue by gfanti** [gfanti/bitcoin#3]
Do not use rand() it isn't cryptographic-- use GetRand(range) or FastRandomContext's randrange (esp for using many rand calls)
(thanks gmaxwell for this suggestion)

**Comment by srya-b** [comment]
Since we currently aren't identifying dandelion nodes correctly at the moment, in using the GetRand function, I set aside a function in `net_processing.cpp` called `GetNextDandelionNode` that all other code can call and until we have a better way of identifying nodes, I put a `IsDandelion` in `CNode` so that we don't have to modify every function as we add dandelion propagation to all the different ways in which transactions can be processed/relayed (through receiving them or the various forms of rpc calls). Just a thought to make it easier.

An issue with this is that some functions are already given a `connman` to call and others use a global `g_connman`. I don't know if there is really a different between the two or why some use one over the other but that might end up a potential problem if not addressed.

**Comment by amiller** [comment]
Fixed in https://github.com/gfanti/bitcoin/commit/2098f3e98486c07b5ce0172d95ac40fae161bd1b
