### ISSUE TITLE
Stemset access concurrency unsafe

### ISSUE THREAD

**Issue by gfanti** [gfanti/bitcoin#6]
Accesses to stemset may be concurrency unsafe--what lock is protecting it from concurrent access?

(thanks gmaxwell for this suggestion)

**Comment by amiller** [comment]
Let's see.... can stemset be accessed from multiple threads?

`stemSet` is accessed from `ProcessMessage` which is the main thread
https://github.com/gfanti/bitcoin/blob/f667c6523497cc0eb9e28a783e4ce331fdbbad38/src/net_processing.cpp#L1229

It is also access from the "Wallet", which is certainly on a different thread. So, certainly at least `stemSet` needs to be locked.
https://github.com/gfanti/bitcoin/blob/f667c6523497cc0eb9e28a783e4ce331fdbbad38/src/wallet/wallet.cpp#L1634

Are there any existing locks we could reuse for this purpose? Otherwise I'd say we should use a new lock `CS_STEMSET`.

**Comment by gfanti** [comment]
Just a minor point, but if we create a new lock, perhaps we can create one for all Dandelion data structures (i.e., maybe `CS_DANDELION`)? I think we will likely need one down the line when we implement the random clocks for robustness to black hole attacks.

**Comment by amiller** [comment]
The new embargo mechanism https://github.com/gfanti/bitcoin/commit/41ef8dd367dd3ac989c31b00befad61438b56aaa avoids having any new `CNode` fields. The `mapEmbargo` and `mapEmbargoExpire` data structures are protected by `cs_main`.
