### ISSUE TITLE
Dandelion inv messages

### ISSUE THREAD

**Issue by gfanti** [gfanti/bitcoin#8]
Dandelion messages might need to be another inv type, rather than a new kind of inv (currently DINV).
(thanks gmaxwell for this suggestion)

**Comment by amiller** [comment]
The CInv object looks like `CInv(int typeIn, const uint256& hashIn)`,
where `typeIn` seems to correspond to either `MSG_TX` (1) or `MSG_BLOCK` (2). These are also a subset of the item types found in `GetDataMsg`.

```
enum GetDataMsg
{
    UNDEFINED = 0,
    MSG_TX = 1,
    MSG_BLOCK = 2,
    // The following can only occur in getdata. Invs always use TX or BLOCK.
    MSG_FILTERED_BLOCK = 3,  //!< Defined in BIP37
    MSG_CMPCT_BLOCK = 4,     //!< Defined in BIP152
    MSG_WITNESS_BLOCK = MSG_BLOCK | MSG_WITNESS_FLAG, //!< Defined in BIP144
    MSG_WITNESS_TX = MSG_TX | MSG_WITNESS_FLAG,       //!< Defined in BIP144
    MSG_FILTERED_WITNESS_BLOCK = MSG_FILTERED_BLOCK | MSG_WITNESS_FLAG,
};
```

Actually the comment `// The following can only occur in getdata. Invs always use TX or BLOCK.` found in the above looks misleading, since elsewhere the `typeIn` field has more structure.
https://github.com/bitcoin/bitcoin/blob/c0ddd32bf629bb48426b0651def497ca1a78e6b1/src/protocol.cpp#L176

**Comment by amiller** [comment]
I think what is happening is that an `INV` network message only only carries a `CInv` object with type `MSG_TX` or `MSG_BLOCK`, however `CInv` objects appearing in a `GETDATA` message can carry other types. So, we should look to define a new `CInv` type that does not conflict with those used in `GetDataMsg`, but that also can be carried in an `INV` message.

**Comment by amiller** [comment]
After looking through BIP37 and BIP144, I will propose we simply add `MSG_DANDELION_TX = 5,` to this `GetDataMsg` enum. And then we also allow INV messages to contain `CInv(5, ...)` objects indicating a dandelion stem.

**Comment by amiller** [comment]
This is implemented in https://github.com/gfanti/bitcoin/commit/3ff7b460e2b80476422ab738926e5fb2f8260aa9
