### ISSUE TITLE
Implement random timers

### ISSUE THREAD

**Issue by gfanti** [gfanti/bitcoin#9]
Add random timers for robustness to black hole attacks.

**Comment by amiller** [comment]
The embargo expiration mechanism is now implemented in https://github.com/gfanti/bitcoin/commit/a3d2a39b8ade6b44ebd524791aa939a5560b2130

We now maintain a data structure `typedef std::multimap<int64_t, uint256> MapEmbargo` that maps expiration times to embargoed transaction hashes. In the `SendMessages` function which is triggered every 100ms or so, we loop over all the expired embargoes, and remove the embargo (and relay each transaction if it is in mempool).

To help clean up the embargo structure, we also maintain a `mapEmbargoExpire` indexed by tx hash, which contains an iterator into `mapEmbargo`. To set the embargo time, we first check to see if any existing parents are embargoed, and if so, make sure that the child's embargo time is greater (to help prevent transactions from getting relayed out of order if possible).

I'll leave this issue open, since the embargo time is still a *fixed* 30 seconds, rather than an exponential function, but that should be easy to add later.

**Comment by gfanti** [comment]
Made the delay a random variable constructed as the sum of a fixed 10 second delay (`EMBARGO_FIXED_DELAY`) plus an exponential delay of mean 15 seconds (`EMBARGO_MEAN_DELAY`). We can change these constants later as needed depending on per-hop latency measurements in the stem. 

Fixed in commit
https://github.com/gfanti/bitcoin/commit/9afa8e05815127ccdef656f87c0bf655c915e852
